2021-11-22T21:04:41.0548326+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-22T21:04:41.1499483+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-11-22T21:04:41.1500298+05:30  [INF] Content root path: "C:\Users\mayanka\Desktop\Pratice\Onion\Onionar" (b5d60022)
2021-11-22T21:04:42.5599180+05:30 80000125-0006-fd00-b63f-84710c7967bb [INF] Log Information to Debug Window! (824a485f)
2021-11-22T21:04:42.5614819+05:30 80000125-0006-fd00-b63f-84710c7967bb [WRN] Log Warning to Debug Window! (2f1d893d)
2021-11-22T21:04:42.5615099+05:30 80000125-0006-fd00-b63f-84710c7967bb [INF] My error (a3e1b752)
2021-11-22T22:16:08.4120872+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-22T22:16:08.4449664+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-11-22T22:16:08.4450550+05:30  [INF] Content root path: "C:\Users\mayanka\Desktop\Pratice\Onion\Onionar" (b5d60022)
2021-11-22T22:16:08.6089571+05:30 8000007d-000b-fe00-b63f-84710c7967bb [INF] Log Information to Debug Window! (824a485f)
2021-11-22T22:16:08.6101701+05:30 8000007d-000b-fe00-b63f-84710c7967bb [WRN] Log Warning to Debug Window! (2f1d893d)
2021-11-22T22:16:08.6101920+05:30 8000007d-000b-fe00-b63f-84710c7967bb [INF] My error (a3e1b752)
2021-11-22T22:39:23.7091943+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-22T22:39:23.7169599+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-11-22T22:39:23.7170185+05:30  [INF] Content root path: "C:\Users\mayanka\Desktop\Pratice\Onion\Onionar" (b5d60022)
2021-11-22T22:39:23.8760167+05:30 8000009f-0004-f800-b63f-84710c7967bb [INF] Log Information to Debug Window! (824a485f)
2021-11-22T22:39:23.8772350+05:30 8000009f-0004-f800-b63f-84710c7967bb [WRN] Log Warning to Debug Window! (2f1d893d)
2021-11-22T22:39:23.8772668+05:30 8000009f-0004-f800-b63f-84710c7967bb [INF] My error (a3e1b752)
2021-11-22T22:41:28.4325247+05:30 80000141-0007-fe00-b63f-84710c7967bb [ERR] The view '"GetListwithStoreProcedure"' was not found. Searched locations: ["/Views/Home/GetListwithStoreProcedure.cshtml", "/Views/Shared/GetListwithStoreProcedure.cshtml"] (9bb2756c)
2021-11-22T22:41:28.8432453+05:30 80000141-0007-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'GetListwithStoreProcedure' was not found. The following locations were searched:
/Views/Home/GetListwithStoreProcedure.cshtml
/Views/Shared/GetListwithStoreProcedure.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-22T22:44:32.3555299+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-22T22:44:32.3631839+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-11-22T22:44:32.3632385+05:30  [INF] Content root path: "C:\Users\mayanka\Desktop\Pratice\Onion\Onionar" (b5d60022)
2021-11-22T22:44:32.5263137+05:30 80000064-000a-fe00-b63f-84710c7967bb [INF] Log Information to Debug Window! (824a485f)
2021-11-22T22:44:32.5275261+05:30 80000064-000a-fe00-b63f-84710c7967bb [WRN] Log Warning to Debug Window! (2f1d893d)
2021-11-22T22:44:32.5275518+05:30 80000064-000a-fe00-b63f-84710c7967bb [INF] My error (a3e1b752)
2021-11-22T22:45:16.7534233+05:30 80000074-0003-fb00-b63f-84710c7967bb [ERR] The view '"GetListwithStoreProcedure"' was not found. Searched locations: ["/Views/Home/GetListwithStoreProcedure.cshtml", "/Views/Shared/GetListwithStoreProcedure.cshtml"] (9bb2756c)
2021-11-22T22:45:16.8947104+05:30 80000074-0003-fb00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'GetListwithStoreProcedure' was not found. The following locations were searched:
/Views/Home/GetListwithStoreProcedure.cshtml
/Views/Shared/GetListwithStoreProcedure.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-22T22:46:03.5636923+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-11-22T22:46:03.5716410+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-11-22T22:46:03.5717170+05:30  [INF] Content root path: "C:\Users\mayanka\Desktop\Pratice\Onion\Onionar" (b5d60022)
2021-11-22T22:46:03.7332148+05:30 80000068-000a-fe00-b63f-84710c7967bb [INF] Log Information to Debug Window! (824a485f)
2021-11-22T22:46:03.7345221+05:30 80000068-000a-fe00-b63f-84710c7967bb [WRN] Log Warning to Debug Window! (2f1d893d)
2021-11-22T22:46:03.7345483+05:30 80000068-000a-fe00-b63f-84710c7967bb [INF] My error (a3e1b752)
2021-11-22T22:46:26.0637431+05:30 8000005c-0009-fe00-b63f-84710c7967bb [ERR] The view '"GetListwithStoreProcedure"' was not found. Searched locations: ["/Views/Home/GetListwithStoreProcedure.cshtml", "/Views/Shared/GetListwithStoreProcedure.cshtml"] (9bb2756c)
2021-11-22T22:46:26.2100806+05:30 8000005c-0009-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'GetListwithStoreProcedure' was not found. The following locations were searched:
/Views/Home/GetListwithStoreProcedure.cshtml
/Views/Shared/GetListwithStoreProcedure.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-22T22:46:34.9783377+05:30 8000003a-0000-ff00-b63f-84710c7967bb [ERR] The view '"GetListwithStoreProcedure"' was not found. Searched locations: ["/Views/Home/GetListwithStoreProcedure.cshtml", "/Views/Shared/GetListwithStoreProcedure.cshtml"] (9bb2756c)
2021-11-22T22:46:35.0798628+05:30 8000003a-0000-ff00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'GetListwithStoreProcedure' was not found. The following locations were searched:
/Views/Home/GetListwithStoreProcedure.cshtml
/Views/Shared/GetListwithStoreProcedure.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-11-22T22:47:05.8800487+05:30 8000006a-000a-fe00-b63f-84710c7967bb [ERR] The view '"GetListwithStoreProcedure"' was not found. Searched locations: ["/Views/Home/GetListwithStoreProcedure.cshtml", "/Views/Shared/GetListwithStoreProcedure.cshtml"] (9bb2756c)
2021-11-22T22:47:05.9860454+05:30 8000006a-000a-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'GetListwithStoreProcedure' was not found. The following locations were searched:
/Views/Home/GetListwithStoreProcedure.cshtml
/Views/Shared/GetListwithStoreProcedure.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
